---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'Jinja2 templating playbook'

  # Target: where our play will run and options it will run with
  hosts: all
  gather_facts: true

  # Task: the list of tasks that will be executed within the playbook
  tasks:       
     - name: Ansible Jinja2 for range, reversed (simulate while greater 5)
       debug:
         msg: >
              --=== Ansible Jinja2 for range , reversed(continue if odd)  ===---
              
              {% for entry in range(10, 0, -1) -%}
                 {% if entry is odd -%}
                     {% continue %}
                 {% endif -%}
                 {{ entry }}
              {% endfor %}               
               

# Three dots indicate the end of a YAML document
...
