---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'Jinja2 templating playbook'

  # Target: where our play will run and options it will run with
  hosts: ansnode1
  gather_facts: true

  # Task: the list of tasks that will be executed within the playbook
  tasks:       
     - name: Ansible Jinja2 for filters 
       debug:
         msg: >
              --=== Ansible Jinja2 filters  ===---
     - name: min value --== min [1,2,3,4,5] ===---
       debug:
         msg: >         
              {{ [1,2,3,4,5] | min }}
     - name: max value {{ [1,2,3,4,5] | max }}
       debug:
         msg: >
              {{ [1,2,3,4,5] | max }}
     - name: --== unique [1, 1, 2, 2, 3, 3, 4, 4, 5, 5] ==--
       debug:
         msg: >
              {{ [1, 1, 2, 2, 3, 3, 4, 4, 5, 5] | unique }}
     - name: --== difference [1, 2, 3, 4, 5] vs [2, 3, 4, 5] ==--
       debug:
         msg: >
              {{ [1, 2, 3, 4, 5] | difference([2, 3, 4]) }}
     - name: --== random['rob', 'jane', 'freddy'] ==--
       debug:
         msg: >
              {{ ['rob', 'jane', 'freddy'] | random }}
     - name: --== urlsplit hostname ==--
       debug:
         msg: >
              {{ "http://docs.ansible.com/ansible/latest/playbooks_filters.html" | urlsplit('hostname') }}
               
               

# Three dots indicate the end of a YAML document
...
