all:
  hosts:
    area51:
      ansible_hostname: area51
      ansible_connection: local
      ansible_all_ipv4_addresses:
        - 10.10.10.1
        - 10.10.10.2
        - 10.10.10.3
    area52:
      ansible_hostname: area52
      ansible_connection: local
      ansible_all_ipv4_addresses:
        - 172.17.0.1
        - 192.168.244.239
        - 192.168.211.140
    area53:
      ansible_hostname: area53
      ansible_connection: local
      ansible_all_ipv4_addresses:
        - 10.10.11.1
        - 10.10.11.2
        - 10.10.11.3
  children:
    webservers:
      hosts:
        area51:
        area52:   
        area53: