all:
  hosts:
    area51:
      ansible_hostname: area51
      ansible_connection: local
      example_variable: "yessss!"
    area52:
      ansible_hostname: area52
      ansible_connection: local
      example_variable: "yessss!"
    area53:
      ansible_hostname: area53
      ansible_connection: local
  children:
    webservers:
      hosts:
        area51:
        area52:   
        area53: