---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'Jinja2 templating playbook'

  # Target: where our play will run and options it will run with
  hosts: webservers
  gather_facts: false

  # Task: the list of tasks that will be executed within the playbook
  tasks:       
     - name: Ansible Jinja2 if
       debug:
         msg: >
              --=== Ansible Jinja2 if elif statement ===---
              {% if ansible_hostname == "area52" -%}
                     This is {{ ansible_hostname }} host
              {% elif ansible_hostname == "area51" -%}
                     This is {{ ansible_hostname }} host with modifications
              {% endif %}

# Three dots indicate the end of a YAML document
...
