---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'Jinja2 templating playbook'

  # Target: where our play will run and options it will run with
  hosts: localhost
  connection: local
  gather_facts: true

  # Task: the list of tasks that will be executed within the playbook
  tasks:       

    - name: Ansible Jinja2 if
      debug:
        msg: >
            {% if inventory_hostname == "localhost" -%}
                    hello localhost
            {% endif %}

# Three dots indicate the end of a YAML document
...
